# lichess_token = "xxxx" # optional
debug = true
sleep_time = 1 # time in seconds, between two calls

[zulip]
email = "xxx@xxx.com"
key = "xxxxxx"
site = "hxxps://YOUR_ZULIP_DOMAIN.com"
channel = "mod-hunter-boost"
topic = "sandbag-bot"