on: [push]

name: CI

jobs:
  build_and_test:
    name: zulip-sandbag-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -vv
      - run: strip target/release/zulip-sandbag-bot
      - uses: actions/upload-artifact@v2
        with:
          name: zulip-sandbag-bot
          path: target/release/zulip-sandbag-bot