on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: zulip-sandbag-bot
          path: "./target/x86_64-unknown-linux-musl/release/zulip-sandbag-bot"